name: deploy

concurrency:
  group: ${{ github.event_name }}

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - manifest.yaml
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master
      - main

permissions:
  id-token: write
  packages: write
  pull-requests: write
  contents: write

jobs:
  
  code_testing:
    uses: ptonini-actions/workflows/.github/workflows/code-tester.yaml@main
    if: github.event.action != 'closed' && github.event.head_commit.author.name != 'github-actions[bot]' && vars.skip_testing != 'true'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  code_linting:
    uses: ptonini-actions/workflows/.github/workflows/code-linter.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action) && vars.skip_linting != 'true'
  security_scan:
    uses: ptonini-actions/workflows/.github/workflows/trufflehog.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
  release_please:
    uses: ptonini-actions/workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'

  publish_frontend:
    uses: ptonini-actions/workflows/.github/workflows/publish-frontend.yaml@main
    if: github.event_name == 'push' && contains(github.event.commits.*.author.name, 'github-actions[bot]')
    secrets:
      NPM_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

  deploy_to_production:
    uses: ptonini-actions/workflows/.github/workflows/deploy-frontend.yaml@main
    needs:
      - publish_frontend
    with:
      version: ${{ needs.publish_frontend.outputs.version }}
      artifact: ${{ needs.publish_frontend.outputs.artifact }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}