name: publish github action

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  publish:
    uses: ptonini-actions/workflows/.github/workflows/github-action.yaml@main