name: publish terraform module

concurrency:  ${{ github.ref }}

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**.tf"

permissions:
  contents: write

jobs:
  publish:
    uses: ptonini-actions/workflows/.github/workflows/terraform.yaml@main
    with:
      action: publish
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}