name: publish python package

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  
  # Code verification #########################################################
  unit-tests:
    uses: ptonini-actions/workflows/.github/workflows/unit-tester.yaml@main
    if: github.event.action != 'closed' && github.event.head_commit.author.name != 'github-actions[bot]' && !vars.skip_testing
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  lint:
    uses: ptonini-actions/workflows/.github/workflows/linter.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action) && !vars.skip_linting
  security-scan:
    uses: ptonini-actions/workflows/.github/workflows/trufflehog.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
  release-please:
    uses: ptonini-actions/workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'

  publish:
    uses: ptonini-actions/workflows/.github/workflows/python.yaml@main
    if: github.event_name == 'push' && contains(github.event.commits.*.author.name, 'github-actions[bot]')