name: apply

concurrency:
  group: ${{ github.repository }}

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main
      - master
    paths-ignore:
      - '.github/workflows/*'

permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:

  lint:
    uses: ptonini-actions/workflows/.github/workflows/code-linter.yaml@main
    if: contains('opened synchronize', github.event.action) && vars.skip_linting != 'true'
  security-scan:
    uses: ptonini-actions/workflows/.github/workflows/action--trufflehog.yaml@main
    if: contains('opened synchronize', github.event.action)

  plan:
    uses: ptonini-actions/workflows/.github/workflows/handler--terraform.yaml@main
    if: contains('opened synchronize', github.event.action)
    with:
      action: plan
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      VAULT_CREDENTIALS: ${{ secrets.VAULT_CREDENTIALS }}
      AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      OPENSTACK_CONFIG: ${{ secrets.OPENSTACK_CONFIG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      TFVARS: ${{ secrets.TFVARS }}

  apply:
    uses: ptonini-actions/workflows/.github/workflows/handler--terraform.yaml@main
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'plan_created')
    with:
      action: apply
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      VAULT_CREDENTIALS: ${{ secrets.VAULT_CREDENTIALS }}
      AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      OPENSTACK_CONFIG: ${{ secrets.OPENSTACK_CONFIG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}