name: apply

concurrency:
  group: apply

on:
  workflow_dispatch: ~

permissions:
  id-token: write
  contents: read

jobs:
  apply-helm-chart:
    uses: ptonini-actions/workflows/.github/workflows/handler--kubernetes.yaml@main
    with:
      action: deploy helm
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      GH_READER_TOKEN: ${{ secrets.GH_READER_TOKEN }}
