name: apply helm release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
      - main
    paths:
      - manifest.yaml

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    uses: ptonini-actions/workflows/.github/workflows/handler--kubernetes.yaml@main
    with:
      action: deploy helm
      environment: ${{ github.event_name == 'pull_request' && 'staging' || 'production' }}
      tag: ${{ github.event_name == 'pull_request' && format('pr{0}', github.event.number) }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      GH_READER_TOKEN: ${{ secrets.GH_READER_TOKEN }}
      VAULT_CREDENTIALS: ${{ secrets.VAULT_CREDENTIALS }}
      AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}