name: deploy

concurrency:
  group: ${{ github.event_name }}

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
      - main
    paths-ignore:
      - manifest.yaml
      - .github/workflows/*
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master
      - main

permissions:
  id-token: write
  packages: write
  pull-requests: write
  contents: write

jobs:

  # Code verification #########################################################
  test:
    uses: ptonini-actions/workflows/.github/workflows/tester--units.yaml@main
    if: github.event.action != 'closed' && github.event.head_commit.author.name != 'github-actions[bot]' && vars.skip_testing != 'true'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  lint:
    uses: ptonini-actions/workflows/.github/workflows/code-linter.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action) && vars.skip_linting != 'true'
  security-scan:
    uses: ptonini-actions/workflows/.github/workflows/action--trufflehog.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
  release-please:
    uses: ptonini-actions/workflows/.github/workflows/action--release-please.yaml@main
    if: github.event_name == 'push'

  # Build and publish docker image ############################################
  publish-image:
    uses: ptonini-actions/workflows/.github/workflows/handler--containers.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
    with:
      action: build-push
      tags: ${{ format('latest pr{0} pr{0}-{1}', github.event.number, github.run_number) }}
    secrets:
      BUILD_ARGUMENTS: |
        BUILD_USERNAME=${{ vars.gh_packages_user }}
        BUILD_PASSWORD=${{ secrets.GH_PACKAGES_TOKEN }}

  # Create staging environment ################################################
  deploy-to-staging:
    uses: ptonini-actions/workflows/.github/workflows/handler--kubernetes.yaml@main
    if: |
      github.event_name == 'pull_request' && contains('opened synchronize', github.event.action) && 
      always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') &&
      vars.skip_staging != 'true'
    needs:
      - publish-image
    with:
      action: deploy helm
      environment: staging
      digest: ${{ needs.publish_image.outputs.digest }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      VAULT_CREDENTIALS: ${{ secrets.VAULT_CREDENTIALS }}
      AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      GH_READER_TOKEN: ${{ secrets.GH_READER_TOKEN }}
  performance-testing:
    uses: ptonini-actions/workflows/.github/workflows/tester--performance.yaml@main
    if: vars.performance_testing == 'true'
    needs:
      - deploy-to-staging
    with:
      host: ${{ needs.deploy_to_staging.outputs.staging_host }}

  # Destroy staging environment ###############################################
  destroy-staging:
    uses: ptonini-actions/workflows/.github/workflows/handler--kubernetes.yaml@main
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && vars.skip_staging != 'true'
    with:
      action: destroy namespace
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}

  # Mark merged pr container image as approved ################################
  approve-image:
    uses: ptonini-actions/workflows/.github/workflows/handler--containers.yaml@main
    if: |
      github.event_name == 'pull_request' && github.event.pull_request.merged && 
      contains(github.event.pull_request.labels.*.name, 'published') && 
      !startsWith(github.event.pull_request.head.ref, vars.release_please_branch_prefix)
    with:
      action: retag
      source_tag: ${{ format('pr{0}', github.event.number) }}
      tags: latest ${{ vars.pr_approved_tag }} ${{ format('pr{0}', github.event.number) }}

  # Set version tag to pr container image #####################################
  promote-image:
    uses: ptonini-actions/workflows/.github/workflows/handler--containers.yaml@main
    if: github.event_name == 'push' && contains(github.event.commits.*.author.name, 'github-actions[bot]')
    with:
      action: retag
      source_tag: ${{ vars.pr_approved_tag }}
      tags: --MANIFEST-VERSION--

  # Deploy container image to production ######################################
  deploy-to-production:
    uses: ptonini-actions/workflows/.github/workflows/handler--kubernetes.yaml@main
    needs:
      - promote-image
    with:
      action: deploy helm
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      GH_READER_TOKEN: ${{ secrets.GH_READER_TOKEN }}