name: publish

on:
  push:
    branches:
      - main
      - master
    paths:
      - images/**

jobs:
  detect_changes:
    uses: ptonini-actions/workflows/.github/workflows/paths-filter.yaml@main
    if: github.event_name == 'pull_request'

  release_please:
    uses: ptonini-actions/workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  publish_images:
    uses: ptonini-actions/workflows/.github/workflows/publish-monorepo-docker-image.yaml@main
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    with:
      path: ${{ matrix.path }}