name: publish

on:
  push:
    branches:
      - main
      - master
    paths:
      - images/**

jobs:
  detect-changes:
    uses: ptonini-actions/workflows/.github/workflows/action--paths-filter.yaml@main
    if: github.event_name == 'pull_request'

  release-please:
    uses: ptonini-actions/workflows/.github/workflows/action--release-please.yaml@main
    if: github.event_name == 'push'

  publish-monorepo-images:
    uses: ptonini-actions/workflows/.github/workflows/handler--containers.yaml@main
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    with:
      repository: ${{ github.repository_owner }}/${{ matrix.path }}
      tags: latest '%MANIFEST_VERSION%'
      path: ${{ matrix.path }}
