name: publish

on:
  push:
    branches:
      - main
      - master
    paths:
      - charts/**

jobs:
  detect_changes:
    uses: ptonini-actions/workflows/.github/workflows/action--paths-filter.yaml@main
    if: github.event_name == 'pull_request'

  release_please:
    uses: ptonini-actions/workflows/.github/workflows/action--release-please.yaml@main
    if: github.event_name == 'push'

  publish:
    uses: ptonini-actions/workflows/.github/workflows/monorepo-publisher--helm.yaml@main
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    with:
      path: ${{ matrix.path }}

  update-repository:
    uses: ptonini-actions/workflows/.github/workflows/repository-updater--helm.yaml@main
    needs:
      - publish_charts