name: publish luarocks monorepo

on:
  push:
    branches:
      - main
      - master
    paths:
      - rocks/**

jobs:
  detect_changes:
    uses: ptonini-actions/workflows/.github/workflows/runner--paths-filter.yaml@main
    if: github.event_name == 'pull_request'

  release_please:
    uses: ptonini-actions/workflows/.github/workflows/runner--release-please.yaml@main
    if: github.event_name == 'push'

  publish:
    uses: ptonini-actions/workflows/.github/workflows/publish-monorepo-luarocks.yaml@main
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    with:
      path: ${{ matrix.path }}

  update-repository:
    uses: ptonini-actions/workflows/.github/workflows/repository-updater--luarocks.yaml@main
    needs:
      - publish_rocks