name: publish helm charts monorepo

on:
  push:
    branches:
      - main
      - master
    paths:
      - charts/**
      - library-charts/**

permissions:
  pull-requests: write
  contents: write

jobs:
  detect_changes:
    uses: ptonini-actions/workflows/.github/workflows/runner--paths-filter.yaml@main
    if: github.event_name == 'pull_request'

  release_please:
    uses: ptonini-actions/workflows/.github/workflows/runner--release-please.yaml@main
    if: github.event_name == 'push'

  publish:
    uses: ptonini-actions/workflows/.github/workflows/handler--helm-chart.yaml@main
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        context: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    with:
      action: build & publish
      context: ${{ matrix.context }}
      repository_url: ${{ vars.repository_url }}
    secrets:
      REPOSITORY_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
      REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}

  update-repository:
    uses: ptonini-actions/workflows/.github/workflows/handler--helm-chart.yaml@main
    needs:
      - publish_charts
    with: 
      action: update dependencies
      gh_pages_owner: ${{ github.repository_owner }}
      gh_pages_repository: ${{ github.event.repository.name }}