name: uninstall

concurrency:
  group: uninstall

on:
  workflow_dispatch: ~

permissions:
  id-token: write
  contents: read

jobs:
  uninstall_release:
    uses: ptonini-actions/workflows/.github/workflows/manage-kubernetes.yaml@main
    with:
      action: uninstall
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}