name: uninstall

concurrency:
  group: uninstall

on:
  workflow_dispatch: ~

permissions:
  id-token: write
  contents: read

jobs:
  uninstall-release:
    uses: ptonini-actions/workflows/.github/workflows/handler--kubernetes.yaml@main
    with:
      action: uninstall helm
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      GH_READER_TOKEN: ${{ secrets.GH_READER_TOKEN }}
      VAULT_CREDENTIALS: ${{ secrets.VAULT_CREDENTIALS }}
      AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}