name: release please

on:
  workflow_call:
    outputs:
      releases_created:
        description: ''
        value: ${{ jobs.release_please.outputs.releases_created }}
      paths_released:
        description: ''
        value: ${{ jobs.release_please.outputs.paths_released }}


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: google-github-actions/release-please-action@v4
        id: release_please
        with:
          command: manifest