name: trufflehog

on:
  workflow_call:
  
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Load extra arguments ##################################################
      - run: |
          [[ ! -e .trufflehog-ignore ]] || echo 'TRUFFLEHOG_EXTRA_ARGS=--exclude-paths=.trufflehog-ignore' | tee -a $GITHUB_ENV
          [[ -z ${RUNNER_DEBUG} ]] || 'TRUFFLEHOG_EXTRA_ARGS+= --debug' | tee -a $GITHUB_ENV

      # Trufflehog action #####################################################
      - uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --max-depth=3 ${{ env.TRUFFLEHOG_EXTRA_ARGS }}