name: create-release

on:
  workflow_call:
    inputs:
      init_version:
        description: ''
        required: false
        default: 1.0.0
        type: string
      tag_partial_versions:
        description: ''
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - run: git config --global user.name "${{ github.actor }}"

      - uses: grumpy-programmer/conventional-commits-semver-release@v1
        id: semver
        with:
          init-version: ${{ inputs.init_version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: tag version
        if: steps.semver.outputs.released
        run: git tag ${{ steps.semver.outputs.tag }}

      - name: tag partial versions
        if: steps.semver.outputs.released && inputs.tag_partial_versions
        run: |
          git tag -f ${{ steps.semver.outputs.tag-prefix }}${{ steps.semver.outputs.version-major }}
          git tag -f ${{ steps.semver.outputs.tag-prefix }}${{ steps.semver.outputs.version-major }}.${{ steps.semver.outputs.version-minor }}

      - name: push tags
        if: steps.semver.outputs.released
        run: git push --tags --force