name: container handler

on:
  workflow_call:
    inputs:
      action:
        description: ''
        required: false
        default: build-push
        type: string
      repository:
        description: ''
        required: false
        default: ${{ github.event.repository.full_name }}
        type: string
      registry:
        description: ''
        required: false
        default: ${{ vars.container_registry }}
        type: string
      tags:
        description: ''
        required: true
        type: string
      source_tag:
        description: ''
        required: false
        type: string
      path:
        description: ''
        required: false
        default: .
        type: string
      release_please_manifest:
        description: ''
        required: false
        default: ${{ vars.release_please_manifest }}
        type: string
    secrets:
      REGISTRY_USERNAME:
        description: ''
        required: false
      REGISTRY_PASSWORD:
        description: ''
        required: false
      BUILD_ARGUMENTS:
        description: ''
        required: false
    outputs:
      digest:
        description: ''
        value: ${{ jobs.handler.outputs.digest }}

env:
  TAGS: ''

jobs:
  handler:
    runs-on: ubuntu-latest

    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3

      # Login to container registry ###########################################
      - uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry == '' && 'ghcr.io' || inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME == '' && github.actor || secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD == '' && github.token || secrets.REGISTRY_PASSWORD }}

      # Build TAGS environment variable ######################################
      - name: build TAGS environment variable
        run: | 
          for T in ${{ inputs.tags }}; do TAGS+="${{ inputs.registry }}/${{ inputs.repository }}: ${T/--MANIFEST-VERSION--/$(jq -r '."${{ inputs.path }}"' < ${{ inputs.release_please_manifest }})},"; done
          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}

      # Build/push container image ############################################
      - if: inputs.action == 'build-push'
        uses: ptonini-actions/build-push-image@v1
        id: build-push
        with:
          tags: ${{ env.TAGS }}
          build-args: ${{ inputs.build_arguments }}
          context: ${{ github.workspace }}/${{ inputs.path }}
      - if: inputs.action == 'build-push' && github.event_name == 'pull_request'
        uses: ptonini-actions/set-labels@v1
        with:
          labels: published

      # Re-tag container image ################################################
      - if: inputs.action == 'retag'
        name: retag image
        run: | 
          export IFS=,
          for T in ${TAGS}; do docker buildx imagetools create ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.source_tag }} --tag ${T};  done
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}