name: container-handler

on:
  workflow_call:
    inputs:
      action:
        description: ''
        required: false
        default: build-push
        type: string
      repository:
        description: ''
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      registry:
        description: ''
        required: false
        default: ghcr.io
        type: string
      username:
        description: ''
        required: false
        default: ${{ github.actor }}
        type: string
      password:
        description: ''
        required: false
        default: ${{ github.token }}
        type: string
      tags:
        description: ''
        required: true
        type: string
      source_tags:
        description: ''
        required: false
        type: string
      path:
        description: ''
        required: false
        default: '.'
        type: string
      rp_manifest_file:
        description: ''
        required: false
        default: ${{ vars.rp_manifest_file }}
        type: string
    secrets:
      BUILD_ARGUMENTS:
        description: ''
        required: false
    outputs:
      digest:
        description: ''
        value: ${{ jobs.container-handler.outputs.digest }}

jobs:
  container-handler:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3

      # Login to container registry ############################################
      - uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      # Create TAGS environment variable ######################################
      - run: | 
          export TAGS
          for T in ${{ inputs.tags }}; do
            [[ ${T} == "%MANIFEST_FILE%"]] && T=$(jq -r '."${{ inputs.path }}"' < ${{ inputs.rp_manifest_file }})"
            TAGS=${{ inputs.repository }}:${T},${TAGS}
          done
          echo "TAGS=${TAGS}" | tee -a $GITHUB_ENV
        shell: bash

      # Build/push container image ############################################
      - if: inputs.action = 'build-push'
        uses: actions/cache@v3
        with:
          path: /tmp/cache
          key: ${{ inputs.repository }}-buildx
      - if: inputs.action = 'build-push'
        uses: docker/build-push-action@v3
        id: build
        with:
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=local,src=/tmp/cache
          cache-to: type=local,mode=max,dest=/tmp/cache-new
          build-args: ${{ inputs.build_arguments }}
          context: ${{ github.workspace }}/${{ inputs.path }}
      - if: inputs.action = 'build-push'
        run: rm -rf /tmp/cache && mv /tmp/cache-new /tmp/cache
        shell: bash

      # Re-tag container image ################################################
      - if: inputs.action = 'retag'
        run: |
          for TAG in ${{ env.TAGS }}; do
            docker buildx imagetools create ${{ inputs.repository }}:${{ inputs.source_tag }} --tag ${TAG}
          done
        env:
          IFS: ,
        shell: bash