name: python-package-publisher

on:
  workflow_call:
    inputs:
      username:
        description: ''
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      password:
        description: ''
        required: false
        type: string
        default: ${{ github.token }}
      repository_url:
        description: ''
        default: ${{ vars.pypi_addr }}
        type: string
      python_version:
        description: ''
        default: ${{ vars.python_version }}
        type: string
        
jobs:
  python-package-publisher:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - uses: actions/checkout@v3

      # Build package #########################################################
      - run: python3 setup.py sdist

      # Upload package to repository ##########################################
      - uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: ${{ inputs.username }}
          password: ${{ inputs.password }}
          repository-url: ${{ inputs.repository_url }}