name: luarock publisher

on:
  workflow_call:
    inputs:
      context:
        description: ''
        required: false
        default: '.'
        type: string
      release_please_manifest:
        description: ''
        required: false
        default: ${{ vars.release_please_manifest }}
        type: string

jobs:
  publisher:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: leafo/gh-actions-lua@10
        with:
          luaVersion: ${{ vars.lua_version }}
      - uses: leafo/gh-actions-luarocks@v4
      - uses: actions/checkout@v3

      # Extract rock name from path ###########################################
      - run: echo "PACKAGE=$(cat rockspec | sed -rn 's/^package = "(.*)"$/\1/p')" >> $GITHUB_ENV

      # Extract version from release-please manifest file #####################
      - run: echo "VERSION=$(jq -r '."${{ inputs.context }}"' ${{ inputs.release_please_manifest }})" >> $GITHUB_ENV

      # Build rock ############################################################
      - run: | 
          tar -czvC rocks -f ${{ inputs.context }}.tar.gz ${PACKAGE}
          envsubst < ${{ inputs.context }}/rockspec > ${PACKAGE}-${VERSION}-1.rockspec
          luarocks pack ${PACKAGE}-${VERSION}-1.rockspec

      # Upload rock to release ################################################
      - run: gh release upload --clobber ${PACKAGE}-v${VERSION} ${PACKAGE}-${VERSION}-*
        env:
          GH_TOKEN: ${{ github.token }}

      # Upload rock to artifact ###############################################
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PACKAGE }}-${{ env.VERSION }}-*