name: publish-terraform-module

on:
  workflow_call:
    inputs:
      tag_partial_versions:
        description: ''
        required: false
        default: false
        type: boolean
      terraform_version:
        description: ''
        required: false
        default: ${{ vars.terraform_version }}
        type: string
    secrets:
      TERRAFORM_CLOUD_TOKEN:
        description: ''
        required: false


jobs:
  publish-terraform-module:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - uses: actions/checkout@v4

      # Initialize module #####################################################
      - run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      # Validate module #######################################################
      - run: terraform validate

      # Create release ########################################################
      - uses: ptonini-actions/create-release@v1
        with:
          tag_partial_versions: ${{ inputs.tag_partial_versions }}