name: publisher-go

on:
  workflow_call:
    inputs:
      app_name:
        description: ''
        default: ${{ github.event.repository.name }}
        required: false
        type: string
      rp_manifest_file:
        description: ''
        required: false
        default: ${{ vars.rp_manifest_file }}
        type: string
      go_builder_image:
        description: ''
        required: false
        default: ${{ vars.go_builder_image }}
        type: string
      go_main_file:
        description: ''
        required: false
        default: ${{ vars.go_main_file }}
        type: string

jobs:
  publisher_go:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v3

      # Extract version from release-please manifest file #####################
      - run: echo "VERSION=$(jq -r '."."' < ${{ inputs.rp_manifest_file }})" | tee -a $GITHUB_ENV

      # Compile application and create checksum ###############################
      - run: | 
          mkdir dist
          docker run -v $(pwd):$(pwd) -w $(pwd) ${{ inputs.go_builder_image }} go build -o dist/${{ inputs.app_name }} ${{ inputs.go_main_file }}
          sha256sum dist/${{ inputs.app_name }} > dist/SHA256SUMS

      # Upload artifact to release ############################################
      - uses: ptonini-actions/upload-release@v1
        with:
          file: dist/${{ inputs.app_name }}
          tag: v${{ env.VERSION }}