name: luarocks repository updater

on:
  workflow_call:

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ vars.lua_version }}
      - uses: leafo/gh-actions-luarocks@v4
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      # Download artifact #####################################################
      - uses: actions/download-artifact@v3

      # Update repository index ###############################################
      - run: luarocks-admin make-manifest --local-tree ${{ github.workspace }}
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .